name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.3+15-4172aba0-SNAPSHOT
org: com.kubukoz
markdown: kramdown
