name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.7.0-M2+3-a49ea62d-SNAPSHOT
org: com.kubukoz
markdown: kramdown
