name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0+14-6f3149b6-SNAPSHOT
org: com.kubukoz
markdown: kramdown
