name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.7.0-M0-TEST+1-4e6fef30-SNAPSHOT
org: com.kubukoz
markdown: kramdown
