name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.3+13-17ececbc-SNAPSHOT
org: com.kubukoz
markdown: kramdown
