name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0+13-ac762bf7-SNAPSHOT
org: com.kubukoz
markdown: kramdown
