name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+1-e701fd28-SNAPSHOT
org: com.kubukoz
markdown: kramdown
