name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.7.0-M0-TEST+9-87544371-SNAPSHOT
org: com.kubukoz
markdown: kramdown
