name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0+19-0484820f-SNAPSHOT
org: com.kubukoz
markdown: kramdown
