name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0+12-3b963a43-SNAPSHOT
org: com.kubukoz
markdown: kramdown
