name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.1+4-cfd9dc49-SNAPSHOT
org: com.kubukoz
markdown: kramdown
