name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1e48da55+20181222-2121-SNAPSHOT
org: com.kubukoz
markdown: kramdown
