name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.7.0-M1+1-8f677ec5-SNAPSHOT
org: com.kubukoz
markdown: kramdown
