name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0+16-89ca5b7c-SNAPSHOT
org: com.kubukoz
markdown: kramdown
