name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2+1-36e7e670-SNAPSHOT
org: com.kubukoz
markdown: kramdown
