name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.7.0-M2+9-ea62b8c3-SNAPSHOT
org: com.kubukoz
markdown: kramdown
