name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+6-775bba21-SNAPSHOT
org: com.kubukoz
markdown: kramdown
