name: sup
baseurl: ''
description: Functional healthchecks in Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.2+4-8b5d6f60-SNAPSHOT
org: com.kubukoz
markdown: kramdown
